# Generated by Django 2.1.5 on 2019-04-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='user_id',
        ),
    ]
